### ISSUE TITLE
Help with automation to set Open/Close time daily based on Sunrise/Sunset

### ISSUE THREAD

**Issue by AnthonyBe** [williamschey/hassio-omlet-smartcoop-door#9]
I've been using my Omlet in Light mode, but like a number of others have voiced in the main community thread (https://community.home-assistant.io/t/omlet-auto-door-for-chicken-coop/191283 and onwards for a few posts), it has its challenges when your coop is under a tree and receives shading. Time of year, latitude, weather conditions, whether the tree is deciduous/non-deciduous, etc. all play a part.

I'm in Sydney, Australia and my coop is under a large deciduous tree (great for shading from summer heat) but I've observed some days where a storm rolls in in the middle of the afternoon (sunset is ~7pm) and the coop closes because the light meter drops to 0. Yes, it re-opens when the storm passes, but you get the point. For many of us, just using Light meter is not always reliable. Equally, I've had 2 occasions in the last few months where due to crazy weather the coop closed early, and I had chickens locked out.

Anyway, it made me appreciate that the better option would be time based, but off course Omlet is missing 2 key factors:

1. Sunrise/sunset calculations
2. Daylight Savings Time changes

So, the link I provided above highlights another community member who made his own integration (shame, not sure why, but that's a different topic) and created a service to set the open and close time based on sunrise and sunset (with any desired offset).

I'm using this integration and would like to attempt the same to try and get a more reliable coop open/close experience for my chooks, however, I lack the skill to do so. I have AC power to my Omlet Smartcoop Door so I'm lucky in that I don't have to worry about power requirements, door going into deep sleep overnight, etc.

I'd really appreciate some help on the best, and simplest way to do this. I imagine if there was a generic and documented way to set this up, quite a few others would also leverage it.
I know there is the Sun HA native integration (https://www.home-assistant.io/integrations/sun) generating entities that can be used to source sunrise/sunset times based on location (sensor.sun_next_rising/sensor.sun_next_setting).

Thanks in advance!

**Comment by williamschey** [comment]
Hi @AnthonyBe ,

You can use an regular automation to set the open and close time each day. Below is an automation that will set the open and close times each day at midday to Sunrise and Sunset times for your location (+ an offset). The offset is specified in seconds, hence the 30 * 60.

```
alias: Chicken Coop Door - Open / Close with Sun
description: ""
triggers:
  - trigger: time
    at: "12:00:00"
conditions: []
actions:
  - action: time.set_value
    metadata: {}
    data:
      time: >
        {{((as_timestamp(states.sun.sun.attributes.next_rising) + (30 * 60) |
        float))  | timestamp_custom("%H:%M:%S")}} 
    target:
      entity_id: time.chicken_coop_chicken_coop_open_time
  - action: time.set_value
    metadata: {}
    data:
      time: >
        {{((as_timestamp(states.sun.sun.attributes.next_setting) + (5 * 60) |
        float))  | timestamp_custom("%H:%M:%S")}} 
    target:
      entity_id: time.chicken_coop_chicken_coop_close_time
mode: single
```
Let me know if have any hassles.

Cheers,
Will
